### ISSUE TITLE
Error on prices of the OTC orders

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1059]
On the % market, says -7% , but well appear these prices( divide the amounts in the order, for example 200 astar ÷ 10 dot = 20$, instead of the correct value on $ 

![Screenshot_20240228_100644_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/72062588-1be2-42a8-85e5-743446d50b3e)
![Screenshot_20240228_100648_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/1c21e05f-3818-4039-8b3b-46653e9ed38c)

**Comment by vkulinich-cl** [comment]
Fixed

**Comment by joseJRJR** [comment]
I still see the bad prices 👀 also i cant deselect the "my order' that also was closed marked like fixed
https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/bb52d677-be11-4c9e-9daa-ba75680a8bf4
